### PR TITLE
delta builder: Move scss import to function that needs it

### PR DESCRIPTION
**Pull request by jokajak**
This allows it to run on systems that don't have Scss set up.

Additionally make the deltaBuilder PEP8 compliant

### CODE REVIEW

**Comment by gcsolaroli** [comment]
Hi @jokajak, I think you have switched indentation from tabs to spaces; is there any REALLY important reason for this change? This is hiding the actual changes you have made to the script.

**Comment by jokajak** [comment]
I switched the tabs to spaces to be PEP8 compliant.

The only real change is moving the scss import to the function but it turns out I accidentally did that when I created the flask backend.

**Comment by gcsolaroli** [comment]
PEP8 says you should "prefer" spaces:
> Tabs should be used solely to remain consistent with code that is already indented with tabs.

As the code was already indented with tabs, I would leave it as is; mostly because I don't stand spaces for indentation purposes. ;)

**Comment by jokajak** [comment]
In that case I've closed the PR :)

**Pull request closed without merging**
